# Generated by Django 4.0.2 on 2022-02-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.CharField(max_length=30),
        ),
    ]
