# Generated by Django 4.0.2 on 2022-02-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdata',
            name='app_id',
            field=models.IntegerField(unique=True),
        ),
    ]
