# Generated by Django 4.0.2 on 2022-02-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_library', '0003_alter_appdata_parent_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdata',
            name='parent_app',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
