# Generated by Django 4.0.2 on 2022-02-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_library', '0004_alter_appdata_parent_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdata',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
