# Generated by Django 4.0.2 on 2022-02-23 15:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games_library', '0006_remove_userappdata_app_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAppData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CMP', 'Completed'), ('PLG', 'Playing'), ('PLD', 'Planned'), ('ONH', 'On Hold'), ('DRO', 'Dropped')], default='PLG', max_length=3)),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2022), django.core.validators.MinValueValidator(1000)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hours_spent', models.FloatField()),
                ('app_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games_library.appdata')),
                ('collections', models.ManyToManyField(through='users_library.AppCollection', to='users_library.Collection')),
            ],
        ),
        migrations.AddField(
            model_name='appcollection',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_library.userappdata'),
        ),
        migrations.AddField(
            model_name='appcollection',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_library.collection'),
        ),
    ]
