# Generated by Django 4.0.2 on 2022-02-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_admin',
        ),
    ]
