# Generated by Django 4.0.2 on 2022-03-04 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_library', '0005_alter_useraccount_is_superuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserApps',
            new_name='UserApp',
        ),
    ]
