# Generated by Django 4.0.2 on 2022-03-04 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_library', '0006_remove_userappdata_app_data_and_more'),
        ('users_library', '0006_rename_userapps_userapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappdata',
            name='app_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='games_library.appdata'),
        ),
    ]
