# Generated by Django 4.0.2 on 2022-03-04 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_library', '0007_alter_userappdata_app_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='apps',
        ),
        migrations.AddField(
            model_name='userappdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserApp',
        ),
    ]
