# Generated by Django 4.0.2 on 2022-03-04 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_library', '0006_remove_userappdata_app_data_and_more'),
        ('users_library', '0008_remove_useraccount_apps_userappdata_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappdata',
            name='name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='userappdata',
            name='app_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games_library.appdata'),
        ),
    ]
